:workflows-url: https://github.com/metanorma/rfc-camelot-holy-grenade-tex/workflows
:actions-url: https://github.com/metanorma/rfc-camelot-holy-grenade-tex/actions
:badges-branch: development

= The Holy Hand Grenade of Antioch (in LaTeXRFC / Metanorma-IETF)

image:{workflows-url}/ubuntu/badge.svg?branch={badges-branch}["Ubuntu build status", link="{actions-url}?query=workflow%3Aubuntu+branch%3A{badges-branch}"]
image:{workflows-url}/macos/badge.svg?branch={badges-branch}["MacOS build status", link="{actions-url}?query=workflow%3Amacos+branch%3A{badges-branch}"]
image:{workflows-url}/windows/badge.svg?branch={badges-branch}["Windows build status", link="{actions-url}?query=workflow%3Awindows+branch%3A{badges-branch}"]

This document is available in its rendered forms here:

* https://metanorma.github.io/rfc-camelot-holy-grenade-tex/[The Holy Hand Grenade of Antioch (HTML)]
* https://metanorma.github.io/rfc-camelot-holy-grenade-tex/draft-camelot-holy-grenade.txt[TXT]
* https://metanorma.github.io/rfc-camelot-holy-grenade-tex/draft-camelot-holy-grenade.nits[NITS]
* https://metanorma.github.io/rfc-camelot-holy-grenade-tex/draft-camelot-holy-grenade.xml[RFC XML v2]
//* https://metanorma.github.io/rfc-camelot-holy-grenade-tex/draft-camelot-holy-grenade.rxl[Relaton XML (Bibliographic item)]

This Internet-Draft is written in
https://datatracker.ietf.org/doc/draft-ribose-asciirfc/[AsciiRFC]
using the https://www.metanorma.com[Metanorma framework], via the
https://github.com/metanorma/metanorma-ietf[`metanorma-ietf` gem].

== Quick Start

For a blank slate start of your Internet-Draft written in AsciiRFC:

1. Clone this repository
2. Copy out all the files (including the dot-files)
3. Done!

== Usage

=== Fetching The Document

[source,sh]
----
git clone https://github.com/metanorma/rfc-camelot-holy-grenade-tex
----

=== Installing Build Tools

You will need to install Metanorma, `xml2rfc` and `idnits` (for submission preflight).

Please see https://www.metanorma.com for installation instructions.

=== On macOS

[source,sh]
----
brew install idnits
brew install python
easy_install pip
pip install -r requirements.txt
gem install bundler
bundle install
----

=== Building The Document

[source,sh]
----
make all
----

=== Checking Against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool
prior to submissions.

The `make` target finds exactly the document name from the `:name:`
document attribute and puts the file in the right place before calling
`idnits` to prevent it complaining about the location.

[source,sh]
----
export ID_NAME=asciirfc-minimal
make draft-${ID_NAME}.nits
----

=== Checking For Invalid / Unicode Characters

[source,sh]
----
export ID_NAME=asciirfc-minimal
pcregrep --color='auto' -n "[\x80-\xFF]" draft-${ID_NAME}.xml
----

=== Iterating The Document

[source,sh]
----
export ID_NAME=asciirfc-minimal
make clean all; open draft-${ID_NAME}.txt
----

