name: macos

on: [push, pull_request]

jobs:
  test-macos:
    name: Test on MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5.7']
        perl: ['5.30']
    steps:

      - name: Checkout repo
        uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Dump cpanm cacheable folder
        run: |
          echo $PERL_MM_OPT
          echo $PERL_MB_OPT
          perl -V
          cpanm --no-interactive --notest Module::Build
          echo $PERL_MM_OPT
          echo $PERL_MB_OPT
          perl -V
  


      - name: Symlink libxml to libxml2
        run: |
          ln -s "$(xcrun --show-sdk-path)/usr/include/libxml2/libxml/" "$(xcrun --show-sdk-path)/usr/include/libxml"
  
      # NOTE: we need LaTeXML including commit
      # https://github.com/brucemiller/LaTeXML/commit/9a0e7dc5829c1218e409da716d2a50b81472c38e
      # related to issue https://github.com/brucemiller/LaTeXML/issues/1153
      # but that's planned for release on 0.85 (early 2020).
      - name: Install LaTeXML
        run: cpanm --verbose --no-interactive --notest git://github.com/brucemiller/LaTeXML.git@9a0e7dc5

      - name: "Run latexml: tex => xml"
        run: |
          latexml draft-camelot-holy-grenade.tex --output=draft-camelot-holy-grenade.xml --preload=tex2mn/Metanorma.cls --preload=tex2mn/Metanorma.cls.ltxml --nocomments

      - name: "Run latexmlpost: xml => adoc"
        run: |
          latexmlpost draft-camelot-holy-grenade.xml --destination=draft-camelot-holy-grenade.adoc --stylesheet=tex2mn/Metanorma.xsl --nocrossref --nodefaultresources

      - name: Setup Metanorma
        run: |
          brew tap metanorma/metanorma
          brew install metanorma

      - name: "Run metanorma: adoc => xml (RFC V3) "
        run: |
          metanorma compile --type=ietf --extensions=rfc draft-camelot-holy-grenade.adoc

      # - name: Setup Ruby ${{ matrix.ruby }}
      #   uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ matrix.ruby }}
      #     architecture: 'x64'

      # - name: Cache gems
      #   id: cache-gems
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ runner.tool_cache }}/Ruby/2.5.7/x64/lib/ruby/gems
      #     key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}

      # - name: Update gems
      #   run: |
      #     gem install bundler -v "~> 2"
      #     bundle update --bundler
      #     bundle install --jobs 4 --retry 3

      # - name: Run specs
      #   run: |
      #     bundle exec rake test
