name: windows

on: [push, pull_request]

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5.7']
        perl: ['5.30']
    steps:

      - name: Checkout repo
        uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      # NOTE: this is a trick I learned from
      #   * https://github.com/skaji/perl-github-actions-sample/blob/master/.github/workflows/windows.yml#L21
      #   * https://medium.com/@skaji/perl-meets-github-actions-3893ae100205
      # It works because shogo82148's action uses Strawberry Perl for Windows.
      - name: Add Strawberry Perl to PATH (*before* MSYS Perl!)
        run: |
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"

      # NOTE: we need LaTeXML including commit
      # https://github.com/brucemiller/LaTeXML/commit/9a0e7dc5829c1218e409da716d2a50b81472c38e
      # related to issue https://github.com/brucemiller/LaTeXML/issues/1153
      # but that's planned for release on 0.85 (early 2020).
      - name: Install LaTeXML
        run: cpanm --verbose --no-interactive --notest git://github.com/brucemiller/LaTeXML.git@9a0e7dc5

      - name: "Run latexml: tex => xml"
        run: |
          latexml draft-camelot-holy-grenade.tex --output=draft-camelot-holy-grenade.xml --preload=tex2mn/Metanorma.cls --preload=tex2mn/Metanorma.cls.ltxml --nocomments

      - name: "Run latexmlpost: xml => adoc"
        run: |
          latexmlpost draft-camelot-holy-grenade.xml --destination=draft-camelot-holy-grenade.adoc --stylesheet=tex2mn/Metanorma.xsl --nocrossref --nodefaultresources
